---
title: "Homework 2"
author: "Jing Leng"
date: "September 18, 2014"
output: pdf_document
---
###1.  
b). 
```{r echo = FALSE}
library(MASS)
mu <- c(3,4)
sigma <- matrix(c(1.0,0.8,0.8,1.0),nrow=2)
datam <- data.frame(mvrnorm(100,mu,sigma))
colnames(datam) <- c("x","y")
```
```{r fig.width = 6, fig.height=5}
plot(datam$x, datam$y, xlim = c(0, 7), ylim = c(0, 7), type = 'p', xlab = "x", ylab = "y")
lm <- lm(y ~ x, data = datam)
abline(lm)
summary(lm)
```
$\hat{\alpha}$ = 1.63  
$\hat{\beta}$ = 0.79  
$\hat{\sigma}$ = 0.5559
$R^2$ = 0.6092  
Using F-test, the p-value is less than 2.2e-16, thus p-value < 0.05. We reject null hypothesis.  

d). 
```{r}
1 - pt((1-0.79582)/0.06385, 98)
```
p-value < 0.05. We reject the null hypothesis.  

###2. 
a). 
```{r fig.width = 6, fig.height=5}
m0 <- lm(y ~ x -1 , data=datam)
summary(m0)
plot(datam$x, datam$y, xlim = c(0, 7), ylim = c(0, 7), type = 'p', xlab = "x", ylab = "y")
abline(lm)
abline(m0, lty = 2)
```
b). 
```{r}
sum(m0$residuals)
``` 
  
The sum is not 0.  
c).   
```{r} 
sum(m0$residuals * datam$x)
sum(m0$residuals * m0$fitted.values)
```
